### ISSUE TITLE
lack of OpenStreetMap attribution

### ISSUE THREAD

**Issue by iamnunocaldeira** [xyz-relativity/ClimbTheWorld-Android#1]
Hi, nice app and website. Glad you picked OpenStreetMap.
However both on the app and at https://xyz-relativity.github.io/ClimbTheWorld/#map=13/45.50880000000001/-73.554 there's no OpenStreetMap attribution. 
The license requires you attribute OpenStreetMap as in https://www.openstreetmap.org/copyright
Also Mapnik and OpenTopoMap are just cartographic styles of OSM data, you can credit them, but also OpenStreetMap.

Kind regards,

Nuno

**Comment by xyz32** [comment]
Hi Nuno and thanks for the e-mail

The web-app I agree it needs some work. I wrote it just to have something for the IPhone users. And didn't really work for it in a long time.

The android app has a lice section that includes the OpenStreetMap license and other 3rd party library I used. Also the maps display does mention the source of the data on the bottom left corner.
The OpenStreetMap community is also credited in the support-us view.

Let me know if you think I should add more. Or have them in a different format/place.
For the web app, my javascritp skills aren't that good, so I don't know if I will spend the time to figure all that out.

Thanks
