### ISSUE TITLE
Release Source Code

### ISSUE THREAD

**Issue by quizilkend** [xyz-relativity/ClimbTheWorld-Android#4]
Hey there,

are there any plans to release the source code?

I would love to see this on F-Droid.

Best regards
Samuel

**Comment by xyz32** [comment]
Hi,
It is in the plan, I just need some time to go through the git history and remove all private info.

**Comment by quizilkend** [comment]
Nice!

**Comment by xyz32** [comment]
Climb the world is now open source.
